# Generated by Django 5.0.6 on 2024-05-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='varsity',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='varsity',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
