# Generated by Django 5.0.6 on 2024-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_varsity_image_varsity_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varsity',
            old_name='image',
            new_name='image_back',
        ),
        migrations.AddField(
            model_name='varsity',
            name='image_front',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
