# Generated by Django 5.0.6 on 2024-06-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_image_varsity_image_back_varsity_image_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='varsity',
            name='college',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
