# Generated by Django 5.0.6 on 2024-06-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_varsity_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20, null=True)),
                ('varsity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='main.varsity')),
            ],
        ),
    ]
