# Generated by Django 5.0.6 on 2024-06-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varsity',
            name='image_back',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='varsity',
            name='image_front',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
