# Generated by Django 5.0.6 on 2024-06-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_varsity_image_back_alter_varsity_image_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varsity',
            name='image_back',
            field=models.ImageField(null=True, upload_to='varsity/'),
        ),
        migrations.AlterField(
            model_name='varsity',
            name='image_front',
            field=models.ImageField(null=True, upload_to='varsity/'),
        ),
    ]
