# Generated by Django 5.0.6 on 2024-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_varsity_image_back_alter_varsity_image_front'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varsity',
            name='like_count',
        ),
        migrations.CreateModel(
            name='Varsitylike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('like', models.ManyToManyField(blank=True, related_name='likes', to='main.varsity')),
            ],
        ),
    ]
