# Generated by Django 5.0.6 on 2024-06-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='major',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
