# Generated by Django 5.0.6 on 2024-06-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_custom_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='major',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
