# Generated by Django 5.0.6 on 2024-06-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
